version: '3'
services:
    wscassandra-one:
        image: cassandra:3.9
        volumes:
            - cassandra-one:/var/lib/cassandra/
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
        environment:
            - CASSANDRA_CLUSTER_NAME='hcassandra-cluster'
            - CASSANDRA_NUM_TOKENS=256
            - CASSANDRA_BROADCAST_ADDRESS=10.195.35.16,10.195.35.17,10.195.35.18
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=datacenter1
            - CASSANDRA_RPC_ADDRESS=0.0.0.0
        restart: always
    