version: '3'
services:
    hcassandraone:
        image: cassandra:3.9
        hostname: hcassandraone
        command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
        networks:
            - hdatacenterringone
        volumes:
            - hvolumecassandraone:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=hcluster
            - CASSANDRA_BROADCAST_ADDRESS=hcassandraone
            - CASSANDRA_SEEDS=hcassandraone,hcassandratwo,hcassandrathree
            - CASSANDRA_DC=hdatacenterone
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_NUM_TOKENS=256
            - CASSANDRA_RPC_ADDRESS=0.0.0.0
        ports:
            - "7000:7000"
            - "7001:7001"
            - "7199:7199"
            - "9042:9042"
            - "9160:9160"
        deploy:
            placement:
                constraints: [node.hostname == HEPC-UHDH-VM15]    
    hcassandratwo:
        image: cassandra:3.9
        hostname: hcassandratwo
        command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 60; fi && /docker-entrypoint.sh cassandra -f'
        networks:
            - hdatacenterringone
        volumes:
            - hvolumecassandratwo:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=hcluster
            - CASSANDRA_BROADCAST_ADDRESS=hcassandratwo
            - CASSANDRA_SEEDS=hcassandraone,hcassandratwo,hcassandrathree
            - CASSANDRA_DC=hdatacenterone
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_NUM_TOKENS=256
            - CASSANDRA_RPC_ADDRESS=0.0.0.0
        deploy:
            placement:
                constraints: [node.hostname == HEPC-UHDH-VM16]
    hcassandrathree:
        image: cassandra:3.9
        hostname: hcassandrathree
        command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 120; fi && /docker-entrypoint.sh cassandra -f'
        networks:
            - hdatacenterringone
        volumes:
            - hvolumecassandrathree:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=hcluster
            - CASSANDRA_BROADCAST_ADDRESS=hcassandrathree
            - CASSANDRA_SEEDS=hcassandraone,hcassandratwo,hcassandrathree
            - CASSANDRA_DC=hdatacenterone
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_NUM_TOKENS=256
            - CASSANDRA_RPC_ADDRESS=0.0.0.0
        deploy:
            placement:
                constraints: [node.hostname == HEPC-UHDH-VM17]
networks:
    hdatacenterringone:
volumes:
  hvolumecassandraone:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/db/hvolumeone/
  hvolumecassandratwo:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/db/hvolumetwo/
  hvolumecassandrathree:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/db/hvolumethree/